version: '3.4'
services:
  server:
    container_name: pow_server
    hostname: pow_server
    restart: always
    build:
      dockerfile: server.Dockerfile
      context: .
      target: runtime
    env_file: .env
    ports:
      - 7777:7777
  client:
    container_name: pow_client
    hostname: pow_client
    restart: always
    build:
      dockerfile: client.Dockerfile
      context: .
      target: runtime
    env_file: .env
    depends_on:
      - server
